# This is a basic workflow that is manually triggered
name: Remote Jupyter Book

# Controls when the action will run. Workflow runs when manually triggered using the UI
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      directory:
        description: 'Jupyter Book to Release (defaults to whole repository)'
        default: '.'
        required: true
      releasename:
        description: 'Release name'
        required: true
      bookname:
        description: 'Book name'
        required: true
      versionnumber:
        description: 'Version number'
        required: true
      languageid:
        description: 'Language id'
        default: 'EN'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  RemoteBook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish book
        uses: dzsquared/jupyter-publish-action@v0.1.0
        with:
          directory: ${{ github.event.inputs.directory }}
          releasename:  ${{ github.event.inputs.releasename }}
          bookname: ${{ github.event.inputs.bookname }}
          versionnumber: ${{ github.event.inputs.versionnumber }}
          languageid: ${{ github.event.inputs.languageid }}
          githubtoken: ${{ secrets.GITHUB_TOKEN }}
